CREATE TABLE berita (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    judul VARCHAR(255) NOT NULL,

    kategori VARCHAR(100) NOT NULL,

    gambar VARCHAR(255) DEFAULT NULL,

    isi TEXT NOT NULL,

    status ENUM('draft', 'publish') NOT NULL DEFAULT 'draft',

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);